# Generated by Django 3.2.4 on 2021-07-26 11:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classwork', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MailToAdmin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('text', models.TextField()),
                ('from_mail', models.EmailField(max_length=254)),
                ('date', models.DateTimeField(default=datetime.datetime(2021, 7, 26, 14, 7, 49, 110511))),
            ],
        ),
    ]
